### PR TITLE
Follow xo linter rules more strictly

### PR DESCRIPTION
**Pull request by xxczaki**
**What is the purpose of this pull request?**

- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Other, please explain:

This PR removes some of the ignored xo linter rules so that the code is more readable.

**What changes did you make? (provide an overview)**

Removed ignored linter rules and linted the files (including docs).

**Which issue (if any) does this pull request address?**

N/A

**Is there anything you'd like reviewers to know?**

This PR might look rather large. However, most of the changes are actually small.

### CODE REVIEW

**Comment by NotMoni** [comment]
Our Coveralls Coverage decreased by `0.2%` in this PR.

**Comment by xxczaki** [comment]
@NotMoni This was due to instanbul ignore comments not being replaced with c8 ignore comments (we apparently did not change them). Now the coverage is much better ;)

**Comment by NotMoni** [comment]
@xxczaki Oh, Alright Mate. 👍 
lgtm

**Comment by xxczaki** [comment]
This should be merged after #834.

**Pull request merged**
