### PR TITLE
Add credentials field to RequestInit type definition

### PR DESCRIPTION
**Pull request by benmccann**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**

Align the request type with the spec

Fixes a type error we're getting in SvelteKit:
https://github.com/sveltejs/kit/blob/5cd6f11aee6cd5edc5a758a5deb88925d3c9a50e/packages/kit/src/runtime/server/page.js#L59

**Which issue (if any) does this pull request address?**

Closes https://github.com/node-fetch/node-fetch/issues/1113

**Is there anything you'd like reviewers to know?**

### CODE REVIEW

**Comment by eikaramba** [comment]
is there something we can do to speed up this pull request? it currently prevents sveltekit from beeing used in SSR mode for any API where server credentials are necessary.

**Comment by benmccann** [comment]
> it currently prevents sveltekit from beeing used in SSR mode for any API where server credentials are necessary

No it doesn't. I've simply told SvelteKit to ignore the type error from `credentials` missing. If there's some other issue or missing feature it's not blocked by this. That being said, I wouldn't mind getting this change in :smile:

**Comment by LinusU** [comment]
Hmmmm, `credentials` is listed as one of the options that we do not implement.

ref: https://github.com/node-fetch/node-fetch#class-request

Should we really add it to the type definitions if we don't support it? 🤔

**Comment by jimmywarting** [comment]
> Hmmmm, `credentials` is listed as one of the options that we do not implement.
> 
> ref: https://github.com/node-fetch/node-fetch#class-request
> 
> Should we really add it to the type definitions if we don't support it? 🤔

Have kind of forgotten the credentials option. I'm only now looking back at some old PR's that have never gotten resolved or closed.

Seeing as if we just made a security fix of exposing sensitive headers...

Maybe it is about time that we ship this option and honor the `omit` rule? that is something we could do on the backend.

The other two options: `same-origin` & `include` i guess is not something we could solve cuz we have no concept of an origin on the backend. 

- `same-origin` refers to the website you are currently on.
- and `include` has to do with CORS

b/c we do not have any origin. Both the `same-origin` and `include` would have the same meaning on the backend when you make a request to example.com. 

---

a bit of information from mdn:

> The credentials read-only property of the Request interface indicates whether the user agent should send cookies from the other domain in the case of cross-origin requests.
> 
> Syntax
> - `request.credentials` - A RequestCredentials dictionary value indicating whether the user agent should send cookies from the other domain in the case of cross-origin requests. Possible values are:
> 
> - `omit`: Never send or receive cookies.
> - `same-origin`: Send user credentials (cookies, basic http auth, etc..) if the URL is on the same origin as the calling script. This is the default value.
> - `include`: Always send user credentials (cookies, basic http auth, etc..), even for cross-origin calls.

if a node-fetch developer would do: `fetch(url, { credentials: 'omit', ...options })` then we could strip away cookies from the request and remove the set-cookie from the response.

**Comment by benmccann** [comment]
We use undici now

**Pull request closed without merging**
