### PR TITLE
Specify possible HTTP request methods in types

### PR DESCRIPTION
**Pull request by ImRodry**
**What is the purpose of this pull request?**

- [X] Documentation update (improving types)
- [ ] Bug fix
- [ ] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**
Added a "Methods" type to index.d.ts that covers all the HTTP request methods supported by node-fetch

**Which issue (if any) does this pull request address?**
There didn't seem to be any open issues regarding this

**Is there anything you'd like reviewers to know?**
I know that the method parameter is case insensitive but it's common practice to write HTTP methods in upper case, which is why I only added those, let me know if you want me to change that though.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Any HTTP method is possible, it's not restricted to just a few subsets

**Comment by ImRodry** [comment]
> Any HTTP method is possible, it's not restricted to just a few subsets

Then I can add more but the type string is objectively wrong because not any string is supported

**Comment by jimmywarting** [comment]
> Then I can add more but the type string is objectively wrong because not any string is supported

That is where you are wrong... Spec says:

> There are no restrictions on methods. `CHICKEN` is perfectly acceptable (and not a misspelling of `CHECKIN`). Other than those that are normalized there are no casing restrictions either. `Egg` or `eGg` would be fine, though uppercase is encouraged for consistency.

https://fetch.spec.whatwg.org/#methods

**Comment by jimmywarting** [comment]
There are api that uses SEARCH for rest APIs

**Comment by jimmywarting** [comment]
There are only this  `CONNECT`, `TRACE`, or `TRACK` forbidden methods, but we live on the backend and isn't restricted of what browser puts on us

**Pull request closed without merging**
