### PR TITLE
Create Code of Conduct

### PR DESCRIPTION
**Pull request by tinovyatkin**
Doing my compulsory social work 😊  as my apologies over two inappropriate tone comments in recent PRs. Not sure which email address we should put here for enforcement, so, I've put @jimmywarting who very politely called my attention on this matter.

### CODE REVIEW

**Comment by jimmywarting** [comment]
I have mostly seen myself as a moderator to this repo.

In the beginning bitinn didn't want to adapt es6 syntax way back when we had lower node support, so i didn't want to code with es3-5 style or what it was. but look at us now :) 
but i felt like i wanted to help out in any way i could by:

- keeping track of most things like issues and PR
- making sure we follow the specification
- trying to keep none spec things from ever entering into node-fetch
- giving out suggestion, helping others with questions folks may have.
- format others comment so code blocks looks good.
- reviewing others code.
- making sure we keep a good tone

if i see some issue, pr or comment then i try to ask myself 
- will this have any value
- can it be solved in any another way
- have this been brought up before
instead of flatt out reject/close something i try to give folks a fighting chans to explain themself of why zyx would be useful or better.

If i would help out making commits then it would take too much time from me. 

I'm also quite active on Stackoverflow, before i was the one to ask question but when i became good at javascript, html & css then i started to help out others and now have a score of 19k points :)

**Comment by jimmywarting** [comment]
now as for my review, i think we should rename it to CONTRIBUTING.md and stuff it into the `.github` directory 👍 

https://github.blog/2012-09-17-contributing-guidelines/

**Comment by tinovyatkin** [comment]
@jimmywarting the `Code of Conduct` and `Contributor Guidelines` are different things from GitHub point of view: https://github.com/node-fetch/node-fetch/community
This one actually are generated automatically from the GitHub template for Code of Conduct, so, I assume naming is correct.

**Comment by jimmywarting** [comment]
Oh, okey, take it back

**Pull request merged**
