### PR TITLE
Update pull request template

### PR DESCRIPTION
**Pull request by NotMoni**

### CODE REVIEW

**Comment by jimmywarting** [comment]
After seeing this in use i feel like the checkboxes are abused a bit

first of all, they should really be radio buttons instead. but github don't support it...

checkboxes are more like task that needs to be completed.

Skärmavbild 2020-06-12 kl  21 51 03

And i don't feel like this is the right way to use them... would it be possible to create multiple PR templates instead with more narrow focus on what kind of PR it is?

**Comment by jimmywarting** [comment]
feel like we should remove them, think we can do better

**Comment by jimmywarting** [comment]
if it's a bug fix PR then it would be useful with a template that have something like
```
- [ ] created a test case
- [ ] done code coverage
- [ ] Ready to be reviewed

fixes #000
```

and maybe some html comments or something

**Comment by NotMoni** [comment]
Will do @jimmywarting

**Comment by NotMoni** [comment]
@jimmywarting @tinovyatkin Should we make multiple TEMPLATE or fit them all in one ?

**Comment by NotMoni** [comment]
I would like to do all in one.

**Comment by jimmywarting** [comment]
> I would like to do all in one.

ok

**Pull request merged**
