### PR TITLE
Add a missing method when checking if an object is a spec-compliant `FormData` object

### PR DESCRIPTION
**Pull request by xxczaki**
MDN: https://developer.mozilla.org/en-US/docs/Web/API/FormData/has]
Spec: https://xhr.spec.whatwg.org/#dom-formdata-has

### CODE REVIEW

**Comment by jimmywarting** [comment]
OCD kicking in? :P

**Comment by tinovyatkin** [comment]
Not exactly related to this PR, but I think we should start this discussion again 😄 
I'm pretty skeptical about this way of object testing that we are using in `node-fetch`. It's completely different things to check an object provided by an environment (`DOM` for example) just by `Symbol.toStringTag` vs concluding out of this symbol that some object will act as we believe in an environment where it doesn't belong natively.
Should we test methods arguments too (`set.length`)?
I would prefer to have some small reference implementations of `Blob`, `FormData`, and `AbortSignal` inside the `node-fetch` and just do `instanceof` - as it can be extended by any developer if needed.
For example, the following class will pass your test perfectly, but will not work as expected:

```js
class FormData extends URLSearchParams {
  get [Symbol.toStringTag]() {
    return "FormData";
  }
}
```

**Comment by jimmywarting** [comment]
> I would prefer to have some small reference implementations of Blob, FormData, and AbortController inside the node-fetch organization and just do instanceof

That would increase the size of node-fetch. And you wouldn't be able to use similar polyfills (hint hint -> #751)

**Comment by tinovyatkin** [comment]
@jimmywarting we have Blob already, FormData (without serialization) is almost complete in my example above and we have serialization built-in into `node-fetch`. `AbortController` is small too.

`instanceof` can be extended by base class via `Symbol.hasInstance` as I did today for `fetch-blob` or can be spoofed via Proxy, as in the example in #848, nothing particularly difficult.

**Comment by jimmywarting** [comment]
@tinovyatkin Would like @bitinn or someone else opinion on that first before we decide on it - create a issue about it first

**Review by LinusU — APPROVED** [review]

**Comment by jimmywarting** [comment]
I don't think this is worth merging if #1314 gets merged.
it basically brings in formdata-polyfill and fixes some stuff like the missing `body.formData()` while also using `symbol.hasInstance` to check if something is a spec compatible formData

this util function got wiped out completely by #1314

**Comment by LinusU** [comment]
Ah, right, #1314 seems to be very close to getting merged so lets close this one ✔️

**Pull request closed without merging**
