### PR TITLE
fix: drop support for Node 12

### PR DESCRIPTION
**Pull request by jimmywarting**
## Purpose
Have created a beta branch and tough to start working on it already

## Changes
- update ci workflow to only test v14.17 and above
- created a v4 limits + upgrade doc

## Additional information
The documentation in v4 upgrade is changes to expect to come, they are not yet fixed...

___

- [x] I updated readme
- [x] I created a upgrade guide
- [x] I change CI workflow to only test node 14.17+
- [ ] start working on this.
___

- part of #1452

### CODE REVIEW

**Comment by jimmywarting** [comment]
Hoping i'm doing this correctly now @gr2m when starting of with the v4 milestone / beta

**Comment by jimmywarting** [comment]
seem like Semantic Pull Request linter didn't like that i used `BREAKING CHANGE:  `

**Comment by gr2m** [comment]
> seem like Semantic Pull Request linter didn't like that i used `BREAKING CHANGE: `

The `BREAKING CHANGE:` needs to go into the commit body, not the commit subject.

**Comment by gr2m** [comment]
No idea why the "Semantic Pull Request" app is still complaining :( I'd ignore it

**Review by gr2m — APPROVED** [review]

**Pull request merged**
