### PR TITLE
perf(form-data): change from repeat 2 to 2 of the thing.

### PR DESCRIPTION
**Pull request by Vetlix**
**What is the purpose of this pull request?**
Improve speed by basically nothing.

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Other, please explain:

**What changes did you make? (provide an overview)**
Look at the changes tab...

**Which issue (if any) does this pull request address?**
Any decently good developer is able to understand that this is slow.

**Is there anything you'd like reviewers to know?**
What were you thinking when you did this?

### CODE REVIEW

**Review by yaboyaxis — APPROVED** [review]
LGTM!

**Comment by wzhouwzhou** [comment]
Since this is a one-time operation, the actual performance overhead should be negligible, or even const folded away. In terms of maintainability or robustness of customisation, a single dash with .repeat(n) allows for easy changing of the `n` argument to test for various dash lengths.
Overall, it's unclear whether this is needed.

**Review by TacticalTechJay — APPROVED** [review]

**Comment by Vetlix** [comment]
willy rude

**Review by tbnritzdoge — CHANGES_REQUESTED** [review]
Pointless pr

**Comment by rpxs** [comment]
perf critical code 😃 😃 😃 :trollface:

**Review by rpxs — COMMENTED** [review]
👍

**Pull request closed without merging**
