### PR TITLE
feat: Add basic middleware functionality

### PR DESCRIPTION
**Pull request by Richienb**
This PR adds basic middleware functionality. I'm not sure how to test this.

### CODE REVIEW

**Comment by bitinn** [comment]
Tests are needed to demonstrate why this feature is needed. I need to know the use case for this to be honest.

**Comment by Richienb** [comment]
> Tests are needed to demonstrate why this feature is needed. I need to know the use case for this to be honest.

@bitinn There's a use case explained here: https://github.com/bitinn/node-fetch/issues/668#issuecomment-533532776

**Comment by jimmywarting** [comment]
Before doing something like this i would want to start on crating a constructor to get a new fetch instance that don't conflict with others `new FetchInstance()`

**Comment by gdoron** [comment]
Also useful for using automatic follow redirect but in the end get all the redirect that there were in the middle.
That's the use-case for me.

**Comment by JefferyHus** [comment]
This is more of `hooks` and not a `middle-ware` design. To be honest I don't see a reason why would someone need such things when it comes to sending `requests`, then comes the `after` hook which is imo is useless, `fetch` returns a promise so you already can execute things after fulfilling your request.

**Comment by LinusU** [comment]
I agree with @JefferyHus, and would like to add that I think that global hooks like this are quite messy. If someone uses this to e.g. parse errors returned from an api, it can easy interfere with any other responses being returned from other parts of the code...

Also, should we really add features that aren't present in the official `fetch` specification? 🤔

**Comment by xxczaki** [comment]
@li

**Comment by xxczaki** [comment]
> Also, should we really add features that aren't present in the official fetch specification? 🤔

@LinusU The main reason why we want to introduce a middleware functionality/hooks is to allow users to set up things like caching/cookies, which are in the spec, but can't be added to node-fetch in an unopinionated way.

**Comment by Richienb** [comment]
We can allow the consumer to specify separate hooks as an option like from [got](https://www.npmjs.com/package/got#hooks).

**Comment by LinusU** [comment]
@xxczaki thanks for the clarification, I still think that it shouldn't be global though. I think that `got`s approach is quite good!

**Comment by xxczaki** [comment]
@LinusU Yeah, I also really like `got` hooks and I think we can take some inspiration from them.

**Review by lastthyme — APPROVED** [review]

**Comment by jimmywarting** [comment]
This PR have been idle for to long (created 2019) and never merged and perhaps outdated as well?. with some consideration i think FetchEvent #370 is better suited - so closing this...

**Pull request closed without merging**
