### PR TITLE
V3 stable release

### LINKED ISSUE #668: v3 Roadmap
**Note: v3 beta is now available on npm under the `next` tag**

---

# v3 Roadmap

## General stuff

- [x] **BREAKING:** Drop support for Node.js 4 and Node.js 6 (#489, #624)
- [x] Update devDependencies (related to #489)
- [x] When users clone(), automatically create streams with custom highWaterMark (#386, PR open: #671)
- [x] Bundle TypeScript types (Support for TypeScript without need of installing `@types/node-fetch` package) (#669)
- [x] Replace Rollup with Microbundle (#643)
- [x] Introduce linting to the project (#303)
- [x] Simplify Travis CI build matrix (related to #431) - Dropping support for Node.js 4 & 6 will help
- [x] Response.statusText should not default (#578)
- [x] Use w3c defined message for AbortError (#657)
- [x] URL is not encoded as UTF-8 (#245)
- Deprecate timeout in favor of AbortController (#523)
- [x] Data URI support (#659)
- [x] Drop the optional dependency on encoding and move charset detection into a separate package. (In progress: [Richienb/fetch-charset-detection](https://github.com/Richienb/fetch-charset-detection) (PR Open: #694))
- [x] Drop existing blob implementation code and use fetch-blob as dependency instead (https://github.com/bitinn/node-fetch/issues/668#issuecomment-529175627)
- [x] Fix stream piping (#309, PR open: #670)
- [x] Fix stream resolving (#642, #665)
- [x] Do not use constructor.name to check object (#667, PR open: #673)
- [x] Properly forward request errors while piping response stream
- [x] Convert `Content-Encoding` to lowercase (#661, PR open: #672)
- [x] More tests for data URI (https://github.com/bitinn/node-fetch/issues/668#issuecomment-529175096)
- [ ] Drop credentials before redirection (#274)
- [x] Modernise the code behind FetchError and AbortError (https://github.com/bitinn/node-fetch/issues/668#issuecomment-530845161)
- [x] Propagate size and timeout to cloned response (#664)
- [x] Replace the calls to `url.parse` and `url.resolve` with calls to `new URL` to use the new UTF-8 awareness and remove the `utf8` package.
    - [x] `url.parse` (https://github.com/node-fetch/node-fetch/pull/701)
	- [x] `url.resolve` (https://github.com/bitinn/node-fetch/commit/e3cd4d22c3f1871fb41b17035ac83b47ad57fdf6)
- [ ] Document types of fetch errors more thoroughly (#549)
- [ ] Should update host if there's a redirection (#570, PR Open: #596)
- [x] **High priority** doesn't correctly handle multiple `content-type` values (#783)

## Additional:

- [ ] HTTP/2 support (#342, PR open: #796)
- [ ] Plugin/middleware system (https://github.com/bitinn/node-fetch/issues/668#issuecomment-533544800, PR open: #677)
- ~~WebStream API support (#387)~~ - needs more discussion and standard.
- ~~Support trailers (#330)~~ - trailer support has been removed (whatwg/fetch#772).
- ~~Caching (#68)~~ - would likely require opinionated implementation.
- ~~Cookies (#94)~~ - would likely require opinionated implementation.

## Other

- [x] Enable Dependabot to automatically update dependencies if they pass tests and are within an appropriate version range.
- [x] A way to back/sponsor the project (#680)
- ~~Create a final v2 release before releasing v3~~
- [ ] Update upgrade guide
- [ ] Release v1.x version of [Richienb/fetch-charset-detection](https://github.com/Richienb/fetch-charset-detection) before release.
- [ ] Add this package to [DefinitelyTyped/DefinitelyTyped/master/notNeededPackages.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/notNeededPackages.json) since we now ship the typings.

---

cc @bitinn @jimmywarting @TimothyGu @jkantr @gr2m @Richienb

### PR DESCRIPTION
**Pull request by jimmywarting**
## Purpose

Going out of beta and marking v3 as stable

## Changes

package.json version + changelog only

## Additional information

Have kind of forgot what the procedure is to release something on github/npm 
is there some auto release to npm when a github tag is generated or something?
___

- [x] I updated ./docs/CHANGELOG.md
- [ ] Add this to [DefinitelyTyped/DefinitelyTyped/master/notNeededPackages.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/notNeededPackages.json) in a draft PR since we now ship the typings.
- [ ] After merge: 
  - [ ] release to npm
  - [ ] tag a new version on github

___

- Fixes #668

### CODE REVIEW

**Comment by Richienb** [comment]
> Have kind of forgot what the procedure is to release something on github/npm

Since we aren't bundling anything anymore, [np](https://github.com/sindresorhus/np#readme) will come in handy.

**Comment by jimmywarting** [comment]
> Since we aren't bundling anything anymore, np will come in handy.

np was quite large: https://npmgraph.js.org/?q=np
354 Modules!

Would kind of rather have some github workflow automations instead

**Comment by gr2m** [comment]
I can setup semantic-release. I think I suggested it before? I’m a co maintainer of @semantic-release so I can take ownership of that part

**Comment by jimmywarting** [comment]
> I can setup semantic-release. I think I suggested it before? I’m a co maintainer of @semantic-release so I can take ownership of that part

Think that would be grate to have!

**Comment by gr2m** [comment]
> > I can setup semantic-release. I think I suggested it before? I’m a co maintainer of @semantic-release so I can take ownership of that part
> 
> Think that would be grate to have! I say go for it

Unless there are any objections, we can go ahead and merge this PR, then I can do the semantic-release setup in 2nd PR

**Review by tinovyatkin — APPROVED** [review]

**Comment by Richienb** [comment]
Last thing:

- [ ] Add this package to DefinitelyTyped/DefinitelyTyped/master/notNeededPackages.json in a draft PR since we now ship the typings.

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
I can work on the semantic-release setup PR on Thursday.

**Comment by Pencab** [comment]
> Perşembe günü anlamsal yayın kurulumu PR üzerinde çalışabilirim.

**Pull request merged**
