### PR TITLE
Fully test both AbortController implementations, Bump abortcontroller-polyfill to 1.7.1

### PR DESCRIPTION
**Pull request by tekwiz**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Other, please explain: Test improvements

**What changes did you make? (provide an overview)**

1. Setup all AbortController tests to run for both abortcontroller-polyfill and abort-controller implementations to correctly catch and diagnose errors like what happened when abortcontroller-polyfill was bumped to 1.6 and 1.7.0 (see https://github.com/mo/abortcontroller-polyfill/issues/53).  
2. Bumped abortcontroller-polyfill dependency to 1.7.1 since 1.6 and 1.7.0 are breaking

**Which issue (if any) does this pull request address?**

none

**Is there anything you'd like reviewers to know?**

### CODE REVIEW

**Comment by tinovyatkin** [comment]
@tekwiz should we add Node 15.x to the CI and also test native implementation as part of this PR?

**Comment by tekwiz** [comment]
@tinovyatkin We certainly should be able to very easily; however there are other test failures with Node.js 15 that need to be addressed first.

**Comment by tekwiz** [comment]
@tinovyatkin After looking at node.js 15 tests in more detail, it looks like the only issue is in cloning responses, so I've gone ahead and setup the tests for native AbortController.

**Comment by tinovyatkin** [comment]
> @tinovyatkin After looking at node.js 15 tests in more detail, it looks like the only issue is in cloning responses, so I've gone ahead and setup the tests for native AbortController.

Cool, but can you also add Node 15 to the test matrix then? https://github.com/node-fetch/node-fetch/blob/e3335784177d51a11426265586d76e1bafe5ee49/.github/workflows/ci.yml#L17

**Comment by tekwiz** [comment]
> > @tinovyatkin After looking at node.js 15 tests in more detail, it looks like the only issue is in cloning responses, so I've gone ahead and setup the tests for native AbortController.
> 
> 
> 
> Cool, but can you also add Node 15 to the test matrix then? https://github.com/node-fetch/node-fetch/blob/e3335784177d51a11426265586d76e1bafe5ee49/.github/workflows/ci.yml#L17
> 
> 

@tinovyatkin There is still the matter of the 3 response cloning failures with node 15. Until that is properly fixed, node 15 shouldn't be added.

**Review by tinovyatkin — APPROVED** [review]

**Review by xxczaki — APPROVED** [review]

**Pull request merged**
