### PR TITLE
fix: add missing exports subpath "./package.json"

### PR DESCRIPTION
**Pull request by resessh**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**
`require('node-fetch/package.json')` fails because package exports missing "./package.json" sub-path.
My repo which using nuxt needs to read package.json.

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to know?**
It's my first time to send a PR to node-fetch, so please let me know if there is anything to fix.

### CODE REVIEW

**Comment by xxczaki** [comment]
> My repo which using nuxt needs to read package.json.

Could you please share a reason why you need to read `package.json` files from dependencies?

**Comment by resessh** [comment]
This is the repo for the reproduction.
https://github.com/resessh/reproduce-node-fetch-888

Briefly, nuxt checks the version of the package it depends on, and depends on node-fetch.
If nuxt fails to get `package.json` of dependencies, it throws an error and the process dies.

https://github.com/nuxt/nuxt.js/blob/6ab65fbf4f2b0d2348363c43f5c2fe81ef47cbc6/packages/builder/src/builder.js#L218-L224

I don't think it is bug that node-fetch doesn't export `package.json`. However, this is a breaking change, and I would like you to export it if possible.

**Comment by Richienb** [comment]
Fixed in https://github.com/node-fetch/node-fetch/commit/b7076bb24f75be688d8fc8b175f41b341e853f2b

**Comment by resessh** [comment]
@Richienb Thanks!!!

**Comment by Mr1262** [comment]
@Richienb Thanks!!!

**Pull request closed without merging**
