### PR TITLE
Fix(premature close) Redirect failing when response is chunked but empty

### LINKED ISSUE #1220: 3.0.0 beta.10: TypeError: Cannot read property 'body' of null
```js
import fetch from 'node-fetch'

const response = await fetch('https://blog.logrocket.com/feed')
const body = await response.text()

console.log(body)
```

throws
```
file:///root/fetchbug/node_modules/node-fetch/src/index.js:99
			response.body.destroy(error);
			         ^

TypeError: Cannot read property 'body' of null
    at file:///root/fetchbug/node_modules/node-fetch/src/index.js:99:13
    at TLSSocket.<anonymous> (file:///root/fetchbug/node_modules/node-fetch/src/index.js:310:6)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)
```

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0-beta.10
| node             | v14.16.0
| npm              | 7.17.0
| Operating System | archlinux

### LINKED ISSUE #1237: Getting 403 while trying to fetch html data.
**Reproduction**

1.  call a get request to `https://www.novelupdates.com/wp-admin/admin-ajax.php?action=nd_ajaxsearchmain&strType=desktop&strOne=Against%20the%20Gods&strSearchType=series`
2. response `please enable cookies` with status [403]

**Expected behavior**
The request should work as it dose not need any cookies. 
When I am using the regular fetch everything work out really good and I am getting response but when I build an API 
and used `node-fetch` the request above dose not work.

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | node-fetch
| node             | ???? latest
| npm              | ???? latest
| Operating System | Windows, visual code

### PR DESCRIPTION
**Pull request by tekwiz**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**

When an abort signal is given, the test for a properly closed chunked request should be skipped.

**Which issue (if any) does this pull request address?**

- fix #1220
- fix #1064 
- fix #1237

**Is there anything you'd like reviewers to know?**

### CODE REVIEW

**Comment by jimmywarting** [comment]
Going to take a look at this tomorrow.

Just so I know, is #1064 and this PR just a fix to handle a older `node:stream` that dose things incorrectly?
I did see some if `node < x then do this` logic...
If we where to drop support for NodeJS version older than 14.13.1 would this still be relevant?

**Comment by tekwiz** [comment]
@jimmywarting #1064 is actually 2 fixes related to premature close problems.  The first part is to handle the bad ending of chunked transfers, which is applicable to to all Node.js 10-14 (and I haven't tested 16).  The second part is to fix the async iterator issue with Node.js 12.  I will update #1064 to clarify.

**Comment by jimmywarting** [comment]
> The second part is to fix the async iterator issue with Node.js 12

The reason why i asked was that it could be nice to remove the async iterator hack/fix if we decide to remove support for node < 14 sometime later, but i guess NodeJS will have added fetch into core at that point

**Comment by tekwiz** [comment]
> > The second part is to fix the async iterator issue with Node.js 12
> 
> The reason why i asked was that it could be nice to remove the async iterator hack/fix if we decide to remove support for node < 14 sometime later, but i guess NodeJS will have added fetch into core at that point

Yes, we can definitely remove the async iterator hack/fix next year when Node.js 12 goes EOL (https://github.com/nodejs/Release)

**Comment by jimmywarting** [comment]
I downloaded your patch and tried both
```js
fetch('https://blog.logrocket.com/feed')
  .then(r => r.arrayBuffer())
  .then(console.log) 
  // works in browser, Throws in node-fetch with Invalid response body while
  // trying to fetch https://fex.baidu.com/feed.xml: Premature close
```

```js
fetch('https://fex.baidu.com/feed.xml')
  .then(r => r.arrayBuffer())
  .then(console.log) // works in browser, and also this PR
```

**Review by jimmywarting — CHANGES_REQUESTED** [review]
I downloaded your patch and tried both
```js
fetch('https://blog.logrocket.com/feed')
  .then(r => r.arrayBuffer())
  .then(console.log) 
  // works in browser, Throws in node-fetch with Invalid response body while
  // trying to fetch https://fex.baidu.com/feed.xml: Premature close
```

```js
fetch('https://fex.baidu.com/feed.xml')
  .then(r => r.arrayBuffer())
  .then(console.log) // works in browser, and also this PR
```

**Comment by tekwiz** [comment]
@jimmywarting Found the issues.  Please give this fix a try.

**Comment by jimmywarting** [comment]
> @jimmywarting Found the issues. Please give this fix a try.

tested, works fine now

> I'll do some more testing today.
> _Originally posted by @tekwiz in https://github.com/node-fetch/node-fetch/issues/1219#issuecomment-888152634_

Marking as draft then, mark as ready to review when you are done

**Comment by jimmywarting** [comment]
@tekwiz have you run some tests?

**Comment by tekwiz** [comment]
> @tekwiz have you run some tests?

Yes, apologies for the delay.  The day job got in the way.  It turns out the Node.js 16 does a better job of handling bad endings of chunked encodings -- it throws an Error with the simple message "aborted" instead of hanging or timing out.  However, with the nonspecific-ness of that error and for the sake of consistency, my opinion is to leave the `fixResponseChunkedTransferBadEnding` check in place for Node.js 16.

**Comment by jimmywarting** [comment]
> my opinion is to leave the fixResponseChunkedTransferBadEnding check in place for Node.js 16.

Are you saying leave it as is and don't merger this PR?

**Review by jimmywarting — APPROVED** [review]

**Comment by jimmywarting** [comment]
Need at least 2 approvals for it to get merged

**Review by LinusU — APPROVED** [review]
Nice 👍

**Comment by AlenToma** [comment]
Yes at last now, will be greet to check [#1237](https://github.com/node-fetch/node-fetch/issues/1237)

**Comment by jimmywarting** [comment]
Thinking we will skip a beta.11 with this pr (fix) and just publish v3.0.0 (stable) instead
The only beef we have tackle now is regarding ESM vs CJS (#1236)

**Pull request merged**
