### PR TITLE
terimnated connections should propagate into response.body

### PR DESCRIPTION
**Pull request by Gozala**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [x] Other, please explain: Test case for the bug report

**What changes did you make? (provide an overview)**
- Added a test case that illustrates the probem

**Which issue (if any) does this pull request address?**

#1055

~**Is there anything you'd like reviewers to know?**~

### CODE REVIEW

**Comment by tekwiz** [comment]
@Gozala Is this intended to be a draft pull request?  I only see a failing test case for Node 12.  Also, it appears that Node 14 is unaffected by this bug.  Can you confirm?

**Comment by tekwiz** [comment]
@Gozala  Nevermind my previous comment.  I understand what this is for now.  Thank you for the test case.  I may have a solution for this in the works already, but I'll keep you posted.

**Comment by Gozala** [comment]
@tekwiz I did some investigation of this and I think the fix would require lifting this, up into the `response.body` itself: 

https://github.com/node-fetch/node-fetch/blob/d016690cd3ff3cfe48e87ff522379b4c85e402a9/src/body.js#L218-L230

However I was not sure what made sense here as I don't exactly understand rationale behind choosing to use node stream for `response.body` (as opposed to `ReadableStream`) & if propagating those errors was aligned with it.

**Comment by tekwiz** [comment]
This was merged with #1064.

**Pull request closed without merging**
