### PR TITLE
feat: `AbortError`

### LINKED ISSUE #792: `AbortError` is not exported
Hi, I noticed that `FetchError` is exported but `AbortError` is not. This means I'm unable to use the error type. Is this intentional?

(Apologies if this is already fixed in the v3 beta.)

### PR DESCRIPTION
**Pull request by frederikprijck**
## Purpose
Backport of https://github.com/node-fetch/node-fetch/commit/553bb5dc5600b103905e3d40c722ebb387510a63 to v2.

## Changes
Exports the AbortError, which is used internally and thrown on a timeout. https://github.com/node-fetch/node-fetch/blob/2.x/src/index.js#L81

## Additional information
https://github.com/node-fetch/node-fetch/issues/792

___

- [ ] I updated readme
- [ ] I added unit test(s)

___

- fix #792

### CODE REVIEW

**Comment by Richienb** [comment]
@node-fetch/core Is updating v2 like this still a thing we can and should do?

**Review by gr2m — APPROVED** [review]
I don't see a reason not to. As long as it's not a breaking change

**Comment by frederikprijck** [comment]
Following up on my open PRs, any plans to merge this? If not, I can close this.

**Comment by gr2m** [comment]
as there was no objection, I'm going to merge it in 👍🏼 Sorry for the delay

**Pull request merged**
