### PR TITLE
Prevent error when response is null

### LINKED ISSUE #1700: Cannot read properties of null (reading, 'body'). regression in 2.6.7
Just reporting this bug upstream that we've run across in crowdin.

https://github.com/crowdin/crowdin-cli/issues/523

```bash
Downloading java runtime environment for version 11
/Users/shannah/.npm/_npx/e624e2fddcf46226/node_modules/node-fetch/lib/index.js:1519
			destroyStream(response.body, err);
			                       ^

TypeError: Cannot read properties of null (reading 'body')
    at /Users/shannah/.npm/_npx/e624e2fddcf46226/node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (/Users/shannah/.npm/_npx/e624e2fddcf46226/node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:527:28)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

This issue doesn't appear to happen using 2.6.7

To reproduce, you can just create an empty directory and run `npx @crowdin/cli@3.9.2`

### LINKED ISSUE #1701: Bug with 2.6.8 release throwing exceptions in certain cases
Hello,
Recently, we found a bug that was introduced by [release 2.6.8](https://github.com/node-fetch/node-fetch/releases/tag/v2.6.8) (probably due to [this PR](https://github.com/node-fetch/node-fetch/pull/1172)) that makes node-fetch throw an error in some cases.
I was not able to determine why, but it is simple to reproduce.
Here is the exception:
```sh
/Users/mainrop/Documents/node-fetch-2-6-8-bug/node_modules/node-fetch/lib/index.js:1519
			destroyStream(response.body, err);
			                       ^

TypeError: Cannot read properties of null (reading 'body')
    at /Users/mainrop/Documents/node-fetch-2-6-8-bug/node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (/Users/mainrop/Documents/node-fetch-2-6-8-bug/node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

**Reproduction**

Here is a repository I made to reproduce this issue: https://github.com/roptch/node-fetch-2-6-8-bug

1. Clone the repo
2. `nvm use` (the node version in this repo is 16, but also tested with 12 and 18 and the error keeps throwing)
3. `yarn start`
4. See the exception that is thrown

**Expected behavior**

No exception should be thrown.

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.8
| node             | 16.18.0
| npm              | 8.19.2
| Operating System | macOS Big Sur (11.6.7)

**Additional context**

### PR DESCRIPTION
**Pull request by labnol**
## Purpose

Fix for this error.
TypeError: Cannot read properties of null (reading 'body')

## Changes

Check if body exist

## Additional information

___

- [ ] I updated readme
- [ ] I added unit test(s)

___

- fix #1700
- fix #1701

### CODE REVIEW

**Comment by labnol** [comment]
Could be related to https://github.com/node-fetch/node-fetch/issues/1574

**Comment by jimmywarting** [comment]
is there a problem with v3.2.5?

**Comment by roptch** [comment]
Related to: https://github.com/node-fetch/node-fetch/issues/1701

**Review by LinusU — APPROVED** [review]
Nice catch 👍

**Comment by NewEraCracker** [comment]
Can someone please merge this and release 2.6.9 on npm with this fix.

Would close #1700 and #1701

**Pull request merged**
