### PR TITLE
Use generic typings for response.json()

### PR DESCRIPTION
**Pull request by tamas-nemeth**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**
made response json() generic

```typescript
export interface User {
  id: string;
}

async function getUser(id: string) {
  const response = await fetch<User>(`http://localhost/api/user/${id}`);
  return response.json(); // Promise<User>
}
```

no breaking changes. generic is optional

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to know?**

### CODE REVIEW

**Comment by LinusU** [comment]
I think that this is undesirable since it will hide an unsound cast that was previously explicit. Is there a downside to using an `as` cast instead?

```ts
export interface Item {
  id: string;
}

async function getUser(id: string) {
  const response = await fetch(`http://localhost/api/user/${id}`);
  return await response.json() as User;
}
```

**Comment by tamas-nemeth** [comment]
Specifying the response type with a generic is a common pattern with `@angular/common/http`
`axios` and `got` also support that

The benefit of not having to repeat the type assertion when reading the data from the same response object is less relevant here, as `.json()` may only be called once. However, I still think it would be useful to support this pattern.

Also, as the generic is optional, users can still choose to make a type assertion instead.

**Comment by LinusU** [comment]
How do you feel about the fact that one could write code that looks perfectly valid in strict mode TypeScript, but that would fail at runtime?

```typescript
export interface User {
  id: string
  name: {
    first: string
    last: string
  }
}

async function getUser(id: string) {
  const response = await fetch<User>(`http://localhost/api/user/${id}`)
  const user = await response.json()

  console.log(user.name.first) // <-- oops the server actually returned `{ id: 'a', firstName: 'b' }`
}
```

**Comment by junaid1460** [comment]
Really it could be just

```typescript

type ParsedDataType = ReturnType<JSON['parse']> // is any

```

**Comment by sergiojoker11** [comment]
> How do you feel about the fact that one could write code that looks perfectly valid in strict mode TypeScript, but that would fail at runtime?
> 
> ```ts
> export interface User {
>   id: string
>   name: {
>     first: string
>     last: string
>   }
> }
> 
> async function getUser(id: string) {
>   const response = await fetch<User>(`http://localhost/api/user/${id}`)
>   const user = await response.json()
> 
>   console.log(user.name.first) // <-- oops the server actually returned `{ id: 'a', firstName: 'b' }`
> }
> ```

There is very little you can do about that. In fact, the code would also break even without casting at runtime.
At the boundary of a HTTP client, all is uncertain. You will never be able to ensure what the API response is going to be like. (Unless you put more effort in and do something clever involving schemas or something like that. However, that is not the point of this PR) 
IMO, casting for this bit is acceptable. I'd argue very hard If saw casting inside an app though.

**Pull request closed without merging**
